recipeData:
  chartVersion: 0.9.10
  catalog_name: Test Catalog
  catalog_description: A catalog for testing
  recipes:
  - version: 1.0.0
    description: Test Recipe
    components:
      spark:
        version: 3.5.0
        upgrade_from: []
        upgrade_to: []
